### ISSUE TITLE
Support variadics

### ISSUE THREAD

**Issue by jaydenseric** [artdecocode/parser#5]
JSDoc allows use of `...` to document repeatable parameters:

```js
/**
 * Returns the sum of all numbers passed to the function.
 * @param {...number} num - A positive or negative number.
 */
function sum(num) {
    var i = 0, n = arguments.length, t = 0;
    for (; i < n; i++) {
        t += arguments[i];
    }
    return t;
}
```

— https://jsdoc.app/tags-param.html#multiple-types-and-repeatable-parameters

Attempting to parse the `...number` type results in an error:

```
Error: Unexpected token ..
    at parseType (/[redacted]/node_modules/@typedefs/parser/build/lib.js:165:13)
    at parser (/[redacted]/node_modules/@typedefs/parser/build/lib.js:203:10)
    at parse (/[redacted]/node_modules/@typedefs/parser/build/index.js:9:10)
```

The `...` operator is probably used in other situations too, not just parameters.

**Comment by 4r7d3c0** [comment]
hey mate, thanks for the report. well that's because `...number` is not actually a type? There's no _variable_ type in this package, variables are only found in functions. If you convert it to something like 
```js
const type = '...number'
const fn = `function(${type})`
parse(fn)
```
Then the parser will return the function type with the `variableArgs` property.
